### ISSUE TITLE
Sharing and font color

### ISSUE THREAD

**Issue by efrainmarinho12** [afollestad/cabinet#105]
I must say that I like the application.
However, I find a problem when I want to share files inside it.
The only options available are the Beam, Drive and my Inbox.
I wish I could also share via Bluetooth (mostly), or Facebook, or Google+, or Messenger, or Keep or Whatsapp.
I think this and a smoothing in the color of the fonts could let the app perfect.

**Comment by afollestad** [comment]
Cabinet doesn't select apps that are available. It sends an intent to the system and the system shows the user apps that say that are able to handle sharing the file. So it's more than likely an issue with your phone or the apps not correctly handling share intents.
