### ISSUE TITLE
Requests root access when deleting an item that does not actually require root

### ISSUE THREAD

**Issue by denilsonsa** [afollestad/cabinet#107]
1. At the side menu, select *Storage*.
2. Try creating a new file there. It works. Try also deleting it. Also works.
3. Create a file called *foobar* in there.
4. At the side menu, select *Root*. It will show the contents of `/` directory.
5. From there, navigate to `sdcard`. It will show the contents of `/sdcard/` directory, which is actually a symlink to the actual path.
6. Now find *foobar* inside `/sdcard/` and try do delete it. Cabinet complains that it requires root permissions. The same error shows up upon trying to create a file there.

Other file managers don't have this issue, only Cabinet has.

This is also a problem for Samsung tablets that have both internal and external storage:

1. Select *Storage* at the side menu.
2. Tap `^` to go up one directory.
3. From there, open `ExtSdCard` directory.
4. Try deleting any file from there… Cabinet complains it requires root permissions. This is incorrect, as other file managers can create/modify/delete files from that directory just fine.

**Comment by afollestad** [comment]
Right not, SD card is root.

https://github.com/afollestad/cabinet/issues/18
