### ISSUE TITLE
Bad encoding for german letters ä ö ü for folder and file names

### ISSUE THREAD

**Issue by flashback2k14** [afollestad/cabinet#111]
App Version 1.8.7.2

![screenshot_2015-01-28-16-14-25](https://cloud.githubusercontent.com/assets/6609359/5940123/fe9a7ab0-a708-11e4-8e49-78a27bcbf822.png)

**Comment by afollestad** [comment]
I don't think there's much that can be done about this. Cabinet only displays what the OS gives to it, nothing is done related to encoding or anything.
