### ISSUE TITLE
Dark theme bug

### ISSUE THREAD

**Issue by asdfzz** [afollestad/cabinet#112]
Hi..if i change color from last version (using black theme) cabinet will stuck with black screen..and i must delete data/cache.

No problem using white theme.

Moto g 5.0.1 gpe stock.

**Comment by revanmj** [comment]
Same here, Galaxy Nexus with AOSP 5.0.2

**Comment by asdfzz** [comment]
Here a screenshot
http://postimg.org/image/takq2hxib/

**Comment by strikeentco** [comment]
Same on Nexus 5 (5.0.1)

**Comment by asdfzz** [comment]
As i have seen,deve know about that bug looking on commits

**Comment by afollestad** [comment]
I completely forgot to fix that before publishing the update. I'll try to
fix it ASAP.

**Comment by afollestad** [comment]
I found the source of the issue. It's due to an infinite Activity recreate() because it thinks the theme was changed even when it wasn't.

**Comment by mcl21014** [comment]
Good. I just emailed the developer on Play, and since he's busy, I've been redirected here. Didn't know it was tied to the black theme. Someone could look into it.

On a related note, do donations in the app go to the community, or the old developer?

**Comment by afollestad** [comment]
@mcl21014 I'm the developer, I have an auto reply setup in my email since most of the time I'm busy in college classes. Donations go directly to me :)

**Comment by afollestad** [comment]
This issue should be fixed now.
