### ISSUE TITLE
Missing toolbar shadow

### ISSUE THREAD

**Issue by plusCubed** [afollestad/cabinet#122]

**Comment by afollestad** [comment]
This has also already been fixed, at least for API 21+ (using elevation)

**Comment by plusCubed** [comment]
I have a fix for <5.0 using a gradient drawable I created. I'll pull request in a few hours when I'm home.

**Comment by afollestad** [comment]
Oh cool, sounds good

**Comment by afollestad** [comment]
Made another issue for this with some more details: https://github.com/afollestad/cabinet/issues/127
