### ISSUE TITLE
USB OTG 

### ISSUE THREAD

**Issue by MrWhite6** [afollestad/cabinet#126]
Would be nice if you add USB OTG for nexus devices. Currently I use another app for that (Nexus USB OTG File Manager), but not nearly as good looking as your app. Also, I noticed you added color to navigation bar, can you add an option to be transparent? (see: http://s13.postimg.org/sore877pz/Screenshot_2015_01_31_19_36_23.png) 

Thanks!

**Comment by afollestad** [comment]
This is a duplicate of https://github.com/afollestad/cabinet/issues/18

**Comment by afollestad** [comment]
Currently a translucent navigation bar would complicate things, unfortunately
