### ISSUE TITLE
Accent color for UI elements such as check boxes and search view (while maintaining material animations)

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet#134]
The checkboxes in the settings menu and the searchbar in the file manager are currently black. Would be nice if they had the same colour as the FAB, etc. (accent colour).

**Comment by afollestad** [comment]
I think there was another issue for this, but unfortunately that's not possible at the moment.

AppCompat only allows them to be colored through the static themes, you can't color them at runtime without custom selectors which would be complicated and disable the Material animations.

**Comment by afollestad** [comment]
I do this in the settings screen and dialogs using programatic tricks, unfortunately there's no easy tricks for checkboxes and stuff.

**Comment by afollestad** [comment]
Can't be done for now
