### ISSUE TITLE
Put 'Cut' in file select action bar for all devices

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet#135]
On devices like the Nexus 4 (1280x768 resolution), you have to tap the overflow button and then select cut, instead of being able to just choose 'Cut' from the action bar. Could you put 'Cut' in there permanently, or at least when there's enough space?

**Comment by afollestad** [comment]
It already goes there if the phone thinks it has enough space, so if it's not there Android thinks there's so space. It should appear on tablets.

**Comment by afollestad** [comment]
This is seen here: https://github.com/afollestad/cabinet/blob/master/app/src/main/res/menu/main_cab.xml#L24
