### ISSUE TITLE
More lollipop animations

### ISSUE THREAD

**Issue by asdfzz** [afollestad/cabinet#136]
It will make cabinet to a new level :)

**Comment by afollestad** [comment]
That's a pretty broad issue, that could mean anything. There's already a few in there, such as the ripple effects on list items.

**Comment by asdfzz** [comment]
Sry you are right..i didnt see ripple because i generally press on icon for select..
At least add ripple when click on items..or an animation switching from folders.

**Comment by afollestad** [comment]
Gonna close this since this is basically inevitable between me and one of the major contributors.
