### ISSUE TITLE
Auto-refresh for local directory content

### ISSUE THREAD

**Issue by warpdesign** [afollestad/cabinet#146]
This description was modified by @afollestad:

Cabinet should auto refresh directory contents every time the `DirectoryFragment` resumes (even when you press back to go to a previous directory), not only when you go into a directory initially or when settings are changed. This will also mean scroll position has to be persisted during refresh. Remote directories will *not* auto-refresh in order to save bandwidth and battery usage, and optimize speed.

**Comment by afollestad** [comment]
https://github.com/afollestad/cabinet/issues/53

**Comment by afollestad** [comment]
Oops, misread this initially

**Comment by warpdesign** [comment]
Thanks!
