### ISSUE TITLE
Rename functions shouldn't allow path delimeter in name

### ISSUE THREAD

**Issue by betrave468** [afollestad/cabinet#156]
Unable to rename a file if you put "/" in the name.

**Comment by arkon** [comment]
You shouldn't be able to, that's the path delimiter.

**Comment by afollestad** [comment]
Yeah, that's how you separate directories in a path (e.g. /sdcard/DCIM). Somehow we'll have to prevent users from typing that in.

**Comment by afollestad** [comment]
Fixed.

![rsz_screenshot](https://cloud.githubusercontent.com/assets/1820165/6047169/8a2420c2-ac6d-11e4-9e6f-cd47bea2c5dd.png)

**Comment by betrave468** [comment]
Well now we know. ☺
