### ISSUE TITLE
Use accent color for folders, as an alternative to the primary color

### ISSUE THREAD

**Issue by mushypeas** [afollestad/cabinet#159]
A very simple suggestion, to make folders look nicer. Could you change the "Coloured Folders" tick box in settings to a menu, which allows you to use no colour, the primary or accent colour. I personally think that folders would look a lot nicer in the accent colour instead of primary, in order to make things more colourful, but I guess everyone has their opinions :)

You can see two screenshots of what I am (trying) to talk about here:

http://imgur.com/fDkpyNn
http://imgur.com/3Qu5fxf

Thanks a lot!

**Comment by afollestad** [comment]
This is now implemented and will be available in the next release
