### ISSUE TITLE
Show the go up icon while in selected mode. 

### ISSUE THREAD

**Issue by pigeonlips** [afollestad/cabinet#162]
Just an idea, but from time to time I miss the **^** icon that takes you up to the parent folder while i have something selected. 

This is normally while i'm moving files about deep in sub-folder's. Currently I work around this by using the side menu and going to somewhere much higher in the tree and back down to where I need to go which isn't so bad. I have from time time tapped the wrong folder in my haste and so needed to start the process again. While thats me being a bad user :) it would be nice to go up from time to time!

Thought I would add it in case anyone wants to add it. I think there's enough room in the toolbar to add it without it looking cluttered. All the best.

**Comment by pigeonlips** [comment]
![screenshot_2015-02-05-09-47-17](https://cloud.githubusercontent.com/assets/9683809/6049650/53516c6a-ad1e-11e4-8e61-03a25680d10d.png)
![screenshot_2015-02-05-09-47-25](https://cloud.githubusercontent.com/assets/9683809/6049652/58128ab8-ad1e-11e4-8e4f-0e9f113c2d80.png)

**Comment by afollestad** [comment]
Good idea!

And thank you

**Comment by pigeonlips** [comment]
![screenshot_2015-02-05-09-47-17](https://cloud.githubusercontent.com/assets/9683809/6049710/cf2493bc-ad1e-11e4-9417-0dff3943e537.png)

**Comment by pigeonlips** [comment]
Wow that was fast - thanks Afollestad. 

Also nice work. I think its a really good file manager, and a great implementation of material design.

**Comment by afollestad** [comment]
Thanks again.

The 'Go Up' option is lower priority than delete/copy/cut/share so it will be inside the overflow menu on most phones. However, it will be fully visible once you tap copy or cut.

![collage](https://cloud.githubusercontent.com/assets/1820165/6049921/3e554fcc-ac81-11e4-9fec-68616a432250.jpg)

This will be in tonights release.

**Comment by pigeonlips** [comment]
Hi, 

I know you're all done with this one, but thought i'd add my thoughts on the chevron-up icon used for going up a level.

The first time I used the app I didn't know where icon for the parent folder was as i assumed that the current chevron-up icon was to collapse the menu or something to do with the UI. Not that it took me to long to work out :)

I had often thought that the chevron-left might look better, but its completely an individual perspective thing. May be if someones good with design they could come up with a new one rather than using the stock icons. 

not sure if overlaying 2 assets would work

![ic_up - example](https://cloud.githubusercontent.com/assets/9683809/6052446/cfb5ac94-ad37-11e4-8af4-e1582487a3f3.png)

![ic_up - example 3](https://cloud.githubusercontent.com/assets/9683809/6052479/2fd6045c-ad38-11e4-9e7b-6e28e95de844.png)

![ic_up - example 2](https://cloud.githubusercontent.com/assets/9683809/6052418/8ee70514-ad37-11e4-84dc-d2b824960441.png)

Just a thought. No expectation here.
