### ISSUE TITLE
Settings description text gets cut off in portrait mode.

### ISSUE THREAD

**Issue by Xorok** [afollestad/cabinet#173]
Hi, the description text in the App settings gets cut off in Portrait mode. If you turn the device to Landscape it shows the rest.

![screenshot_2015-02-05-01-57-21](https://cloud.githubusercontent.com/assets/9898278/6053348/749c1b1c-acde-11e4-9de5-04880c7384a5.png)
![screenshot_2015-02-05-01-57-48](https://cloud.githubusercontent.com/assets/9898278/6053347/748267da-acde-11e4-982d-dd428a19b54a.png)
![screenshot_2015-02-05-01-57-44](https://cloud.githubusercontent.com/assets/9898278/6053349/74c65814-acde-11e4-9591-9b2ea92f9d77.png)

**Comment by afollestad** [comment]
This is fixed and will be available whenever the next update is published
