### ISSUE TITLE
Directory count spacing not consistent.

### ISSUE THREAD

**Issue by Xorok** [afollestad/cabinet#175]
Not sure if this is still relevant, since #167 would already fix this too.
"Verzeichnis - 1 Datei
Verzeichnis -3 Dateien
Verzeichnis -2 Dateien"

![screenshot_2015-02-05-01-59-19](https://cloud.githubusercontent.com/assets/9898278/6053490/45c86636-ace0-11e4-9497-c1995467c6e2.png)

**Comment by afollestad** [comment]
This won't apply to a slightly newer update that should already be available.
