### ISSUE TITLE
Darker accent colors cause issues with text readability

### ISSUE THREAD

**Issue by mcl21014** [afollestad/cabinet#179]
I don't exactly know what specific setting is triggering this hard to read text, but I can give you some screenshots. Notice how the selected item in the sidebar is next to impossible to read.
![tmp_6363-screenshot_2015-02-04-22-21-32611265174](https://cloud.githubusercontent.com/assets/3611312/6054549/f98e7e2c-acbc-11e4-870a-ec446fc7e414.png)
![tmp_6363-screenshot_2015-02-04-22-27-251297633975](https://cloud.githubusercontent.com/assets/3611312/6054556/07a19c74-acbd-11e4-9d26-b4c777b8e6a8.png)

**Comment by afollestad** [comment]
It uses whatever your accent color is there, I'd recommend using a brighter accent color. I'll have to find someone around that, maybe by limiting the colors that can be used for accent colors.
