### ISSUE TITLE
When in select mode, clicking another item doesn't select it

### ISSUE THREAD

**Issue by mderazon** [afollestad/cabinet#180]
Press and hold to select an item
Then press (not hold) another item
Expected behavior : the second item should be added to the selection list.
What happens instead : cabinet show "open with" dialog box.

**Comment by afollestad** [comment]
It's been discussed many times why this is not the case.

**Comment by afollestad** [comment]
Like the tutorial says, you can use single tap by tapping icons. This functionality allows you to move between folders while using selection mode (and copy/cut and paste).

**Comment by mderazon** [comment]
I get it, just felt unnatural for me (even with the icons tapping)
Take Google's inbox app as an example.
Anyway, no biggie...
