### ISSUE TITLE
Folders change color

### ISSUE THREAD

**Issue by Xorok** [afollestad/cabinet#187]
Some of the visible folders are blue (is this intentional?) but as soon as you open a folder and then go back they're grey too.
(-Apparently-depending-on-the-first-letter-in-their-name...-
*Changes every time you switch folders and go back)

![screenshot_2015-02-05-22-43-10](https://cloud.githubusercontent.com/assets/9898278/6069986/36d361a4-ad89-11e4-9245-407c22b39acd.png)
![screenshot_2015-02-05-22-43-15](https://cloud.githubusercontent.com/assets/9898278/6069993/4571efdc-ad89-11e4-96d6-056b8f4a96af.png)

**Comment by afollestad** [comment]
Hmmm, that's definitely not intentional. Thanks for reporting this.

**Comment by Xorok** [comment]
No problem :)

**Comment by afollestad** [comment]
Does this happen with the latest version? Is there any noticeable triggers?

**Comment by afollestad** [comment]
Closing this for now since I can't reproduce it.
