### ISSUE TITLE
Deletion not working correctly for folders?

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet#192]
It appears to correctly delete contents, but the dialog never closes (in latest code) and the original folder never gets removed from the list.

**Comment by plusCubed** [comment]
It also seems to be broken for files if you try to delete two files one after another. I think this is due to the indexes not updating. 

Currently fixing these 2 bugs... I'll push fixes when done.

**Comment by afollestad** [comment]
Cool, sounds good, thanks
