### ISSUE TITLE
The position of the FAB is not perfect.

### ISSUE THREAD

**Issue by Sh4dowSoul** [afollestad/cabinet#193]
Hey Aidan, 
the FAB should be moved a little bit to the bottom and to the right. On the screenshots you can see what I mean. At the right side it should be aligned to the third keyline and at the bottom to the second normal line (thats "fab_margin" 2dp instead of 16). For testing i suggest you: https://play.google.com/store/apps/details?id=com.faizmalkani.keylinepushing

![screenshot_2015-02-06-06-14-43](https://cloud.githubusercontent.com/assets/10466533/6086236/58135984-ae40-11e4-9174-e00771bda2e7.png)
![screenshot_2015-02-06-06-14-04](https://cloud.githubusercontent.com/assets/10466533/6086235/5812e8aa-ae40-11e4-95ac-5c927325ca05.png)

**Comment by afollestad** [comment]
I decreased the bottom spacing a little, the right side spacing is intended though. It lines up with the menu icons on list items.

**Comment by Sh4dowSoul** [comment]
OK, that makes sense.
