### ISSUE TITLE
Sharing multiple files broken

### ISSUE THREAD

**Issue by plusCubed** [afollestad/cabinet#198]

**Comment by afollestad** [comment]
After this, https://github.com/afollestad/cabinet/issues/19 and https://github.com/afollestad/cabinet/issues/192 are fixed, I will push an update to Google Play

**Comment by afollestad** [comment]
Possibly this too: https://github.com/afollestad/cabinet/issues/25

**Comment by afollestad** [comment]
This was a very simple fix: https://github.com/afollestad/cabinet/commit/2419105599e93f21cd45aa9f4cb2f91771dce897
