### ISSUE TITLE
Make sure the same nav drawer width dimensions are used as what's in Impression

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet#201]
https://plus.google.com/113512419416851876239/posts/QGDB4hjGRXa

**Comment by plusCubed** [comment]
Cabinet's nav drawer width dimensions are correct; Impression is incorrect right now. See [this checklist on the Android Developers blog.](http://android-developers.blogspot.com/2014/10/material-design-on-android-checklist.html)

BTW, the Material Design specs for nav drawer width is incorrect. See my comments [here](https://plus.google.com/wm/1/+AdamKoch/posts/1wxETQQtt6V).

**Comment by afollestad** [comment]
@plusCubed Impression is currently using 304dp which I've seen Google employees mention as correct in various places
