### ISSUE TITLE
Pasting folders into themselves

### ISSUE THREAD

**Issue by plusCubed** [afollestad/cabinet#207]
It doesn't cause a crash, but weird things happen.

~~Solution: prevent opening folders that are selected when copying/cutting~~ See below

**Comment by plusCubed** [comment]
Actually, just prevent pasting folders into themselves because the user might still want to open selected folder and there's no reason to disable opening it.

**Comment by afollestad** [comment]
Good catch, this was a one-line fix luckily (there's a `canPasteIntoSameDir()` method in the CAB files that now returns false for the copy CAB too).

**Comment by plusCubed** [comment]
I don't think the issue is fixed - the user can still copy folder A in the parent directory, go into folder A, and paste.
