### ISSUE TITLE
Pasting multiple files causes all file operations to start at once

### ISSUE THREAD

**Issue by plusCubed** [afollestad/cabinet#208]
I would think it is more efficient to start them one after another, but maybe I'm missing something here.

Either way, the progress dialog is misleading right now because of this (operations are started all at once, so all of them start to finish around the same time, causing the progress dialog to be really slow, then suddenly finish pasting everything).

**Comment by afollestad** [comment]
Oh yeah, I actually didn't intend to do that. I can switch out the async methods for the sync methods quickly before this next release.

**Comment by afollestad** [comment]
Actually we have to stick with the async methods cause they also handle cloud upload. I'll have to do the same thing I do with deletion.

**Comment by afollestad** [comment]
I'll push an update now and deal with this tomorrow

**Comment by afollestad** [comment]
Working on this now

**Comment by afollestad** [comment]
This should now be fixed with the latest commit. I have to test it now. @plusCubed
