### ISSUE TITLE
File / Folder counter improvements

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet#210]
When opening a directory with 1 file in it, it says "1 files" instead of "1 file". It doesn't distinguish between files and directories either, so inside a directory that contains 3 sub-directories and 4 files it will just say "7 files" at the top.
Would be nice if that was fixed.

**Comment by creati8e** [comment]
Also for some folders counter is negative.
![screenshot_2015-02-10-16-36-28](https://cloud.githubusercontent.com/assets/10930232/6128108/5ea79ba6-b143-11e4-8c2b-205489836449.png)

**Comment by afollestad** [comment]
Done for the next update
