### ISSUE TITLE
SMB support

### ISSUE THREAD

**Issue by LucasKeure** [afollestad/cabinet#62]
Can someone add SMB support for file sharing with PC ?

**Comment by Sniperfox47** [comment]
Not sure if it should be appended here but WebDAV and ftp/ftps would be nice down the road as well.

**Comment by mahbubremoS** [comment]
Thanksthttps://source.android.com/images/android_framework_details.pngo the top of my favourite

**Comment by afollestad** [comment]
Merging this with https://github.com/afollestad/cabinet/issues/213
