### ISSUE TITLE
Stretched image preview on grid mode

### ISSUE THREAD

**Issue by mv97** [afollestad/cabinet#80]
I see the bug with image preview streched in grid mode. Here the screenshot from lastest version of Cabiet Beta
![screenshot_2014-11-25-19-36-14](https://cloud.githubusercontent.com/assets/9950711/5188163/5bcf8758-74db-11e4-9604-b4ebb8c7a97a.png)
When open it, text is not stretched.
Screenshot from Nexus 7 2012 running Android 5.0 Lollipop

**Comment by afollestad** [comment]
Let me know if this is fixed in the new version that will be available within an hour or two.

**Comment by mv97** [comment]
Yes, i see, that not streched, but cropped.
