### ISSUE TITLE
LG devices with hardware menu button cause crash

### ISSUE THREAD

**Issue by anonymous-user** [afollestad/cabinet#83]
I have an LG Optimus L9 running Android 4.1.2 and am affected by this bug:

https://code.google.com/p/android/issues/detail?id=78154

I cannot access the main menu and thus the Settings window and whatever else is in the menu. This is a serious issue for me.

**Comment by afollestad** [comment]
Sorry, there's not an easy way to fix this. I'd recommend upgrading your phone, this is an OEM issue.

**Comment by anonymous-user** [comment]
Every other dev that I asked to fix this has been able to do it. I believe there is some code you can try in the link I posted.

**Comment by afollestad** [comment]
Oh yeah you're right, it's implemented, let me know if it works for you when the new update is available. Should be in a few hours.
