### ISSUE TITLE
Assistant install apk

### ISSUE THREAD

**Issue by ElfsRage** [afollestad/cabinet#86]
Hello, this is my return:
Application with a great design and very simple. But it lacks some features, such as a launching a .apk file menu when showing both applications version numbers (that of the apk and the application already installed), and the same with the Signature applications .... through a small dialog with the material design, as you know so well, that would be impeccable. (Like es file explorer solid and explore ....) and there it will want 5 star, but for now I remain on those applying located above.
Pending a new version.
Best Regards

source french : 
Bonjour, voici mon retour : 
Application avec un super design et très simple. Mais elle manque quelques fonctionnalités, comme par exemple un menu lors du lancement d'un ficher .apk qui montre les deux numéros de version des applications (celui de l'apk et celui de l'application déjà installé) et la même chose avec la signature des applications.... par l'intermédiaire d'une petite boîte de dialogue à la material design, comme vous savez si bien le faire, ça serait impeccable. (A l'instar de es explorateur de fichier et solid explorer,....) et là ça voudra 5 étoiles, mais pour le moment je reste sur ces application situé ci dessus. 
Dans l'attente de votre nouvelle version.
Cordialement

![screenshot_2014-12-15-15-26-56](https://cloud.githubusercontent.com/assets/10145188/5437303/99b0ad56-846f-11e4-9694-77d5923300ed.png)

**Comment by afollestad** [comment]
This isn't necessary, the OS already does that for you.
