### ISSUE TITLE
Can’t authenticate to SFTP

### ISSUE THREAD

**Issue by towolf** [afollestad/cabinet#91]
I have a raspberry pi with Debian openssh sshd (1:6.0p1-4+deb7u2).

I tried all kinds of host names, both IPv6 and IPv4. It just says "Auth Fail" and on the auth.log on the server it shows: 

    sshd[20356]: Received disconnect from 2a02:8070:87c0:9500:49fd:b477:2994:4d93: 3: com.jcraft.jsch.JSchException: Auth fail [preauth]

or 

    sshd[20367]: Received disconnect from 10.0.0.106: 3: com.jcraft.jsch.JSchException: Auth fail [preauth]

**Comment by afollestad** [comment]
This isn't an issue specific to Cabinet, this is a JSch library issue.

**Comment by afollestad** [comment]
Looking at this again, make sure you're using all the correct settings. Again, this would be an issue with a library I'm using, but it's working fine for me.
