### ISSUE TITLE
Please add the Share icon at the top instead of hidden in the menu

### ISSUE THREAD

**Issue by kirko7** [afollestad/cabinet#93]
Hard to even know what's gonna happen if you want to share multiple files.

Off topic... how do you add Labels to issues?  This should be an enhancement

**Comment by caseykulm** [comment]
This kind of clashes with the minimalist ideal.

**Comment by afollestad** [comment]
I agree that it should be more prominent. I'll try to move it out more.

**Comment by afollestad** [comment]
This will be improved in the upcoming update. It now has higher priority than the copy option.
