### ISSUE TITLE
Issue with opening a root folder (LsParser)

### ISSUE THREAD

**Issue by Rhedox** [afollestad/cabinet#95]
When I open a root folder and grant root access using SuperSu I get an error screen saying "length=9; regionStart=6; regionLength=-7"

My device is a i9505 (Samsung Galaxy S4) which is running an unofficial build of CM12.

![image](https://cloud.githubusercontent.com/assets/1131720/5608428/0bac423e-9484-11e4-8df4-c0eab5a99a85.png)

**Comment by afollestad** [comment]
Replacing with this:

https://github.com/afollestad/cabinet/issues/77
