### ISSUE TITLE
Media File Picker enhancement

### ISSUE THREAD

**Issue by Sniperfox47** [afollestad/cabinet#96]
A media file picker for apps such as clock that call on mediastorage would be a nice addition down the road. While not neccesary for the app to replace my existing file explorer it would be a nice addition. That being said, out of the three apps I've used as file managers for extended periods (Astro, FX, and ES) only one (ES) provides this so maybe there's a good reason not to that I'm missing.

**Comment by afollestad** [comment]
Media picker as in displaying images and videos and stuff? I'd recommend using gallery apps for that, such as by new app (Impression) which is not in the Google Play Store but is frequently updated over Google+.

**Comment by afollestad** [comment]
Not clear on what this is or why it's necessary so I'm closing the issue.
