### ISSUE TITLE
CAB overlaps Navigation Drawer

### ISSUE THREAD

**Issue by Blazefrost** [afollestad/cabinet#97]
The contextual action bar hides the first element of the navigation drawer, thus making the first element inaccessible without creating a copy of it.
![screenshot_2015-01-06-00-20-57 1](https://cloud.githubusercontent.com/assets/8116260/5622097/ddd3ed70-953d-11e4-80a1-36f36488a85d.png)

**Comment by afollestad** [comment]
This is fixed for the next release
