### ISSUE TITLE
Contextual action bar color

### ISSUE THREAD

**Issue by jon9066** [afollestad/cabinet#98]
I noticed when you select something in Gmail or Keep the colour of the top changes to gray. In Cabinet for some reason it changes to black with a red line on the bottom. I think that red line is out of place, it doesn't fit with the overall design and doesn't make any sense, so I would appreciate it if it weren't there, or an explanation on what's the deal with it. It actually wasn't where a couple months back.

**Comment by afollestad** [comment]
It will remain blue in the upcoming update, I agree that it looked odd (that was just the default).
