### ISSUE TITLE
Notification bar gets dimmed

### ISSUE THREAD

**Issue by jon9066** [afollestad/cabinet#99]
The notification bar gets dimmed with the rest of the screen when the side menu is pulled out, except for the part that is above the side menu itself. It gets fixed when you select something and then diselect it.

**Comment by afollestad** [comment]
That's not a bug, that's intended

**Comment by jon9066** [comment]
If it's not a bug, why does it change after selecting and deselecting something? Maybe I wasn't clear on my description, here are some screenshots.
![screenshot_2015-01-07-18-37-48](https://cloud.githubusercontent.com/assets/9371940/5649202/bcb6105e-969c-11e4-86df-e617d1a4e4cf.png)
![screenshot_2015-01-07-18-37-53](https://cloud.githubusercontent.com/assets/9371940/5649203/bcb92ab4-969c-11e4-855e-f671bf230d66.png)
